# Generated by Django 4.1.7 on 2023-04-07 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OcelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('events_count', models.IntegerField(null=True)),
                ('objects_count', models.IntegerField(null=True)),
                ('object_types', models.JSONField(null=True)),
                ('attribute_names', models.JSONField(null=True)),
                ('activities', models.JSONField(null=True)),
                ('activities_string', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LogObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('ovmap', models.TextField(null=True)),
                ('ocel_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_Visualisation_App.ocellog')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('activity', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField()),
                ('vmap', models.JSONField(null=True)),
                ('event_objects', models.ManyToManyField(related_name='events', to='Log_Visualisation_App.logobject')),
                ('ocel_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_Visualisation_App.ocellog')),
            ],
        ),
    ]
