# Generated by Django 4.1.7 on 2023-04-07 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Log_Visualisation_App", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(model_name="ocellog", name="activities_string",),
    ]
