# Generated by Django 4.1.7 on 2023-04-03 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Visualisation_App', '0003_event_event_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_name', models.CharField(max_length=255)),
                ('ocel_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Log_Visualisation_App.ocellog')),
            ],
        ),
    ]
