# Generated by Django 4.1.7 on 2023-04-03 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Visualisation_App', '0004_logobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='ocellog',
            name='events_count',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocellog',
            name='objects_count',
            field=models.IntegerField(blank=True, default=11),
            preserve_default=False,
        ),
    ]
