# Generated by Django 4.1.7 on 2023-04-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Visualisation_App', '0005_ocellog_events_count_ocellog_objects_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ocellog',
            name='events_count',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ocellog',
            name='objects_count',
            field=models.IntegerField(null=True),
        ),
    ]
