# Generated by Django 4.1.7 on 2023-04-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Visualisation_App', '0006_alter_ocellog_events_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_value',
            field=models.TextField(default='aaaa'),
            preserve_default=False,
        ),
    ]
