# Generated by Django 4.1.7 on 2023-04-07 12:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Log_Visualisation_App', '0007_event_event_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='event_name',
            new_name='activity',
        ),
        migrations.RenameField(
            model_name='logobject',
            old_name='object_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_value',
        ),
        migrations.RemoveField(
            model_name='ocellog',
            name='log',
        ),
        migrations.AddField(
            model_name='event',
            name='event_objects',
            field=models.ManyToManyField(related_name='events', to='Log_Visualisation_App.logobject'),
        ),
        migrations.AddField(
            model_name='event',
            name='name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 7, 14, 4, 59, 181332)),
        ),
        migrations.AddField(
            model_name='event',
            name='vmap',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='logobject',
            name='ovmap',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='logobject',
            name='type',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ocellog',
            name='activities',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ocellog',
            name='attribute_names',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='ocellog',
            name='object_types',
            field=models.JSONField(null=True),
        ),
    ]
